### ISSUE TITLE
Log-Support for more than one stream at a time

### ISSUE THREAD

**Issue by BenBE** [Florianjw/simple_logger#1]
It would be nice to be able to set more than one active output of the logger at any given time.

``` cpp
logger::set_stream(0, std::out);
logger::note("Only to std::out at this time");
logger::set_stream(1, "/dev/tty1");
logger::note("To std::out and /dev/tty1 for this message");
logger::reset_stream(1);
logger::note("Visible on std::out only again.");
logger::reset_stream(0);
logger::warning("Visible nowhere near you!");
```

Number of channels should be flexible, low number expected, set_stream on stream already present, closes previous stream on that channel.

Management of streams allocated by user is duty of user; streams opened by the logger interface should be handled there. Providing explicit deleter parameter when setting up a stream called when it is closed is desirable and should use sane default implementation.

**Comment by Fiona-J-W** [comment]
Done
