### ISSUE TITLE
Reduce Copy&Paste in Unit Test

### ISSUE THREAD

**Issue by BenBE** [Florianjw/simple_logger#2]
The unit test should be refactored to move the final check of the produced output out into a macro/inline function producing much more concise result check code.

e.g.:

``` cpp
const foo = std::string("string1");
const bar = std::string("string2");

BOOST_CHECK(std::equal(foo.begin(), foo.end(), result.begin()));
BOOST_CHECK(std::equal(bar.rbegin(), bar.rend(), result.rbegin()));
```

should be simplified to something along the lines of:

``` cpp
LOG_CHECK(result, "string1", "string2");
```

**Comment by Fiona-J-W** [comment]
Done
