### ISSUE TITLE
Log target might reference dead object

### ISSUE THREAD

**Issue by BenBE** [Florianjw/simple_logger#3]
The stored reference for the stream used for the output should be aware of when the object/instance it refers to goes out of scope. The current unit test implementation would suffer this dead reference issue if the proper (re-)initialization of the stream was forgotten in even one of the tests.

The current construction is somewhat dangerous ;-)

**Comment by Fiona-J-W** [comment]
Improved by requiring a logger-object that takes a list of lvalue-references in it's ctor. While it is still possible to write broken code, this should make it sufficiently hard to avoid most accidents.
